### ISSUE TITLE
Feature request: addd ability to login to the Docker Hub

### ISSUE THREAD

**Issue by Napas** [pgarbe/cdk-ecr-sync#425]
Use case: buy a single PRO account to avoid rate limiting when synchronizing repositories.

I could code that, just wonder what do you think would be the best approach for that?

My initial thinking is just passing username and password in the EcrSync properties, then refactor CodeBuild specs to:
* if docker hub credential exist - login to the Docker Hub
* pull all the images from the Docker Hub
* login to the ECR
* tag and push all the images to the ECR.

How does that sound? 🤔

**Comment by pgarbe** [comment]
Yes, I also thought about that. So far I did not run into any rate limits, so I saved myself the work. :) But if it's a real issue, I'd be happy to merge some PRs
