### ISSUE TITLE
struggling to get started with this project :(

### ISSUE THREAD

**Issue by kartik-moolya** [pgarbe/cdk-ecr-sync#692]
Can someone please help me how to get started. I went through the readme, did try deploying but nothing worked.
* Basically created a new directory
* did a `npm install @pgarbe/cdk-ecr-sync`
created `test.js` with below contents
```
import * as cdk from '@aws-cdk/core';
import { Duration } from '@aws-cdk/core';
import { EcrSync } from '@pgarbe/cdk-ecr-sync';
// import { EcrSync } from '../src';

export class EcrSyncStack extends cdk.Stack {
  constructor(scope, id, props ) {
    super(scope, id, props)

    // The code that defines your stack goes here
    new EcrSync(this, 'ecrSync', {
      dockerImages: [
        { imageName: 'datadog/agent' },
      ],
      lifcecyleRule: {
        maxImageAge: Duration.days(365),
      },
    });
  }
}

const app = new cdk.App();
new EcrSyncStack(app, 'EcrSyncStack');
```
I had to make the file extentsion to mjs. it did run after than but lambda was not created at all. I did npm install and everything on my local which is cofigured to use my aws account
however it does not work. Can someone help me with a more relevant end to end example please

**Comment by pgarbe** [comment]
This is not a typical ts/js node module but focused on [CDK](https://aws.amazon.com/cdk/). You've to create a new CDK application and reference it there. After that, the CDK application can be deployed to your AWS account and it will create the ECR repositories, the lambda and the CodeBuild to run the syncs.
